### ISSUE TITLE
Does Quack supported for windows environment?

### ISSUE THREAD

**Issue by alwaysharsha** [Autodesk/quack#12]
After installing quack
> python setup.py install

**Running help command fails,**
> quack -h
PS E:\BitBucket\PublicGitHub\Autodesk\quack-master\quack-master> quack
quack : The term 'quack' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ quack
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (quack:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by zonito** [comment]
Looks like PATH is not set for quack. 

Can you please try installing using `pip install quack`?

Thanks
