### ISSUE TITLE
Bug: Doesn't work with submodules

### ISSUE THREAD

**Issue by tomck** [Autodesk/quack#9]
By [removing the .gitmodules file](https://github.com/Autodesk/quack/blob/master/quack/quack.py#L113) this breaks existing submodules. It seems the goal of quack is to not need submodules, but what if you have some items that work better as submodules and some that don't? Perhaps a temporary location for the file would be wise, and putting it back afterward.

**Comment by zonito** [comment]
Yes, the vision for Quack to work with submodule. But I understand we should not delete / change existing implementation of submodule. Will work on it like you suggested.
